### ISSUE TITLE
Cannot install to system paths

### ISSUE THREAD

**Issue by MakisH** [precice/setup-precice-action#3]
With:

```yaml
    - name: Install preCICE
      uses: precice/setup-precice-action@main
      with:
        precice-version: develop
        install-prefix: /usr
```

I get the following error ([logs](https://github.com/precice/openfoam-adapter/actions/runs/5811092510/job/15753512136?pr=299)):

```text
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib/x86_64-linux-gnu/libprecice.so.3.0.0
CMake Error at cmake_install.cmake:72 (file):
  file INSTALL cannot copy file
  "/home/runner/work/openfoam-adapter/openfoam-adapter/precice/build/libprecice.so.3.0.0"
  to "/usr/lib/x86_64-linux-gnu/libprecice.so.3.0.0": Success.


make: *** [Makefile:120: install] Error 1
Error: Process completed with exit code 2.
```

Same with `/usr/local`, which is the mentioned as default in the `README.md`.

I don't know what is the common practice in Actions, but maybe we need a `sudo` before the `make install` [here](https://github.com/precice/setup-precice-action/blob/94df8a6091dc03b1c4405c35119ca6f6721ecab6/action.yml#L118), at least in case this is a system path.
